name: 'Pub Mirror @MeowSauce'

on:
 push:
  branches: [ main ]
 schedule:
   - cron: "0 0 * * *" # 每天凌晨执行

jobs:
 Build:
    runs-on: ubuntu-latest
    steps:
      - name: 检查代码
        uses: actions/checkout@v2
        
      - name: 运行程序
        run: node index.js

      - name: 准备上传
        run: |
          cd src
          mv data.json mirror.json

 Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 上传文件
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:koimarket/koimarket.github.io.git
        BRANCH: main
        FOLDER: src
        SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
