name: 'Pub Mirror @MeowSauce'

on:
 push:
  branches: [ main ]
 schedule:
   - cron: "0 0 * * *" # 每天凌晨执行

jobs:
 Download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build
        run: node index.js

      - name: Rename mirror
        run: |
          cd src
          mv data.json mirror.json

 Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPOSITORY_NAME: koimarket/koimarket.github.io
          BRANCH: main
          FOLDER: public
