name: 'Pub Mirror @MeowSauce'

on:
 push:
  branches: [ main ]
 schedule:
   - cron: "0 0 * * *" # 每天凌晨执行

jobs:
 Build:
    runs-on: ubuntu-latest
    steps:
      - name: 检查代码
        uses: actions/checkout@v2
        
      - name: 运行程序
        run: node index.js

      - name: 准备上传
        run: |
          cd src
          mv data.json mirror.json

 Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 上传构件
        uses: actions/upload-artifact@v4
        with:
          path: src
      - name: 上传源
        env:
         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
         git init
         git add mirror.json
         git remote add target git@github.com:koimarket/koimarket.github.io.git
         git push target HEAD:refs/heads/main -f
